DROP DATABASE IF EXISTS alcool;

CREATE DATABASE alcool
DEFAULT CHARACTER SET = utf8;

USE alcool;

DROP TABLE IF EXISTS questions;

CREATE TABLE questions (
    id INT PRIMARY KEY AUTO_INCREMENT,
    question VARCHAR(255) NOT NULL,
    category VARCHAR (255) NOT NULL
); 

INSERT INTO questions (question, category) VALUES
("Ne pas se laver pendant une semaine", "Qui"),
("Courir à poil sur les Champs-Elysées", "Qui"),
("Brûler un billet de 50 euro pour 10 euro", "Qui"),
("Coucher avec un parents de ses amis", "Qui"),
("Mettre le lait avant les céréales", "Qui"),
("Manger une pizza avec de l'ananas", "Qui"),
("Dire je t'aime sans le penser", "Qui"),
("Prêter facilement son abonnement Netflix", "Qui"),
("Tromper son/sa moitié", "Qui"),
("Devenir président de la république", "Qui"),
("Chanter dans le métro/bus", "Qui"),
("Jouer dans un film pour adultes", "Qui"),
("Survivre à une attaque de zombies", "Qui"),
("Se faire un tattouage sur le front", "Qui"),
("Voyagé hors de l'Europe", "Jamais"),
("Fait de saut en parachute", "Jamais"),
("Consommé de drogue (Y'as pas cool dans drogue)", "Jamais"),
("Conduit en état d'ébriété", "Jamais"),
("Menti pour me sortir d'une situation embarassante", "Jamais"),
("Eté viré d'un bar ou d'une boîte)", "Jamais"),
("Fait arrêter par la police", "Jamais"),
("Envoyé de message embarassant à la mauvaise persone", "Jamais"),
("Menti pour cacher l'infidélité d'un ami", "Jamais"),
("Fait semblant de rire à une blague que je n'avais pas comprise", "Jamais"),
("Vous devez tous vous vouvoyez à partir de maintenant, 1 gorgée à chaque manque !", "Event"),
("Le joueur le plus jeune invente une règle!", "Event"),
("Le joueur le plus vieux invente une règle!", "Event"),
("Le joueur le plus grand invente une règle!", "Event"),
("Le joueur le plus petit invente une règle!", "Event"),
("5 gorgées pour toutes les femmes", "Event"),
("5 gorgées pour tout les hommes", "Event"),
("Il est interdit de regarder son téléphone (sauf pour le jeu) 1 gorgée à chaque oubli", "Event"),
("Tout le monde change de place et boit une gorgée", "Event"),
("Gorgées double pendant 5 rounds !", "Event"),
("Dans Harry Potter, cite 3 sorciers de Gryffondor", "Citation"),
("Dans Harry Potter, cite 3 sorciers de Serpentard", "Citation"),
("Dans Harry Potter, cite 3 sorciers de Serdaigle", "Citation"),
("Dans Harry Potter, cite 3 sorciers de Pouffsouffle", "Citation"),
("Cite 3 antoganistes d'Harry Potter", "Citation"),
("Cite 3 antoganistes de Star Wars", "Citation"),
("Donne le nom de 3 personnages de Friends", "Citation"),
("Cite 3 héros de Star Wars", "Citation"),
("Cite 3 héros de Marvel", "Citation"),
("Cite 3 antagonistes de Marvel", "Citation"),
("Cite 3 antagonistes de DC Comics", "Citation"),
("Cite 3 héros de DC Comics", "Citation"),
("Cite 3 personnages de League of Legends", "Citation"),
("Cite 3 capitales d'Amérique du Sud", "Citation"),
("Cite 3 personnages de Naruto", "Citation"),
("Bois dans tous les verres", "Action"),
("Imite un joueur et laisse les autres deviner de qui il s'agit", "Action"),
("Tu dois dire c'est clair dès que quelqu'un fini de parler pendant 5 rounds", "Action"),
("Fais un calin à tous les joueurs", "Action"),
("Tu choisis la musique de ton choix, personne n'as le droit de la changer", "Action"),
("Tu dois faire 10 pompes", "Action"),
("Chante une chanson de ton choix, les autres jugent", "Action"),
("Lèche ton coude", "Action"),
("Quelle est ta plus grande phobie", "Vérité"),
("Combien de jours as-tu déjà passer sans te laver?", "Vérité"),
("Dans combien de pays as-tu voyagé ?", "Vérité"),
("Combien de shots tu peux t'enfiler à la suite ? Prouve-le !", "Vérité"),
("As-tu djà embrassé une personne du même sexe ?", "Vérité"),
("As-tu déjà triché à un examen ?", "Vérité"),
("Le joueur à ta gauche choisis une question", "Vérité"),
("Le joueur à ta gauche choisis une question", "Vérité"),
("Le joueur à ta gauche choisis une question", "Vérité"),
("Le joueur à ta gauche choisis une question", "Vérité"),
("Le joueur à ta gauche choisis une question", "Vérité"),
("Le joueur à ta droite choisis une question", "Vérité"),
("Le joueur à ta droite choisis une question", "Vérité"),
("Le joueur à ta droite choisis une question", "Vérité"),
("Le joueur à ta droite choisis une question", "Vérité"),
("Le joueur à ta droite choisis une question", "Vérité"),
("Le joueur à ta droite choisis une question", "Vérité"),
("Combien y a t'il d'habitants en Thaïlande ? (à 5 millions près)", "Question"),
("Comment appelle-t-on le bébé du Tigre ?", "Question"),
("Où se trouve le Macchu Pichu ?", "Question"),
("Quel âge à la reine d'Angleterre ?", "Question"),
("Où se trouve Angkor Wat ?", "Question"),
("Qui vit dans un ananas au fond de la mer ?", "Question"),
("Quelle est la capitale de l'Indonésie ?", "Question"),
("Comment s'appelle l'acteur de Néo dans Matrix ?", "Question"),
("De quel héros, Poison Ivy est elle l'ennemi ?", "Question"),
("Qui interprète le Terminator dans le film du même nom ?", "Question"),
("O-Ren Ishii est un personnage de quel film de Quentin Tarantino ?", "Question");
